meta:
  name: NN_FINAL_MEGA_V2_BIO
  strict_fail_closed: true

dataset_groups:
  core_sternberg:
    - ds003655
    - ds004117
    - ds005095
    - ds004796
  mechanism:
    - ds003838
  clinical_rest:
    - ds004504
    - ds004584
    - ds007020
  sternberg_generalization:
    - ds004752
    - ds004469
  workload_expansion:
    - ds007262

analysis:
  lawc_n_perm: 100000
  lawc_n_perm_min: 20000
  lawc_n_perm_adaptive_factor: 10
  lawc_controls: true
  lawc_fail_closed_controls: true

  mechanism_n_perm: 10000
  mechanism_seeds: "0-199"
  mechanism_min_seeds: "0-49"

  normative_seeds: "0-499"
  normative_min_seeds: "0-199"

  clinical_perm: 20000
  clinical_perm_min: 5000
  clinical_perm_workers: 48

  gpu_parallel_procs_min: 8
  gpu_parallel_procs_max: 24
  cpu_workers_default: 32
  cpu_workers_cap_physical: true

runtime:
  defaults:
    preload_gpu_tensors: auto
    use_bf16: true
    try_torch_compile: true
    allow_tf32: true
